name: MobSFScan

on: [push, pull_request]

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Rodar MobSFScan
        uses: MobSF/mobsfscan@0.4.5
        with:
          path: "./"  
          json: true  
          exit_code: true  

      - name: Report
        uses: actions/upload-artifact@v4
        with:
          name: mobsfscan-results
          path: mobsfscan-output.json
