name: MobSFScan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MobSF
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo docker pull opensecurity/mobile-security-framework-mobsf:latest
        sudo docker run -d -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest

    - name: Wait for MobSF to start
      run: sleep 60

    - name: Run MobSFScan
      uses: ajinabraham/mobsfscan-action@v1
      with:
        mobsf_host: 'http://localhost:8000'
        app_path: './app/build/outputs/apk/release/app-release.apk'
